server.port=8080
spring.application.name=hello-world
spring.profiles.active=${APP_ENV:dev}
spring.profiles.include=env
app.hello.message=Hello World!
app.log.incoming.pattern=Incoming request: {} args={}
app.log.outgoing.pattern=Outgoing response: {} result={}

# Springboot 2.0 Actuator Config
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include: metrics, health, info, configprops
management.health.db.enabled=true 
management.endpoint.health.show-details=ALWAYS
management.endpoint.configprops.enabled=true
management.info.git.mode=simple

# Dynamic Scheduling Configuration
component-config.dynamic-scheduling.tasks.alert.enabled=true
component-config.dynamic-scheduling.tasks.alert.cron=0 0/30 * * * *
component-config.dynamic-scheduling.tasks.alert.url=https://localhost:8443/observability-alert-observer/api/sla/status-advice-feedback

component-config.dynamic-scheduling.tasks.item33.enabled=true
component-config.dynamic-scheduling.tasks.item33.cron=0 0 8 * * MON,TUE,WED,THU,FRI
component-config.dynamic-scheduling.tasks.item33.url=https://localhost:8443/observability-item-orchestrator/api/item/item33

component-config.dynamic-scheduling.tasks.item35.enabled=true
component-config.dynamic-scheduling.tasks.item35.cron=0 0 7 * * MON,TUE,WED,THU,FRI
component-config.dynamic-scheduling.tasks.item35.url=https://localhost:8443/observability-item-orchestrator/api/item/item35

component-config.dynamic-scheduling.tasks.item36.enabled=true
component-config.dynamic-scheduling.tasks.item36.cron=0 0 8 * * MON,TUE,WED,THU,FRI
component-config.dynamic-scheduling.tasks.item36.url=https://localhost:8443/observability-item-orchestrator/api/item/item36

component-config.dynamic-scheduling.tasks.alert-eof-started-customer.enabled=true
component-config.dynamic-scheduling.tasks.alert-eof-started-customer.cron=0 0 3 * * 2-6
component-config.dynamic-scheduling.tasks.alert-eof-started-customer.url=https://localhost:8443/observability-alert-observer/api/sla/end-of-day

component-config.dynamic-scheduling.tasks.alert-eof-started-authority.enabled=true
component-config.dynamic-scheduling.tasks.alert-eof-started-authority.cron=0 0 7 * * 2-6
component-config.dynamic-scheduling.tasks.alert-eof-started-authority.url=https://localhost:8443/observability-alert-observer/api/sla/end-of-day

component-config.dynamic-scheduling.tasks.alert-eof-customer.enabled=true
component-config.dynamic-scheduling.tasks.alert-eof-customer.cron=0 0 6 * * 2-6
component-config.dynamic-scheduling.tasks.alert-eof-customer.url=https://localhost:8443/observability-alert-observer/api/sla/end-of-day

component-config.dynamic-scheduling.tasks.alert-eof-authority.enabled=true
component-config.dynamic-scheduling.tasks.alert-eof-authority.cron=0 0 12 * * 2-6
component-config.dynamic-scheduling.tasks.alert-eof-authority.url=https://localhost:8443/observability-alert-observer/api/sla/end-of-day
